linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    # List of functions to exclude from checking.
    exclude-functions:
      - '(*go.uber.org/zap.Logger).Sync'

linters:
  enable:
    - errcheck

run:
  timeout: 5m
  skip-dirs:
    - vendor
  skip-files:
    - generated.go