linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    # List of functions to exclude from checking.
    exclude-functions:
      - '(*go.uber.org/zap.Logger).Sync'

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

run:
  timeout: 5m

issues:
  skip-dirs:
    - vendor
  skip-files:
    - generated.go
