apiVersion: v1
kind: Secret
metadata:
  name: {{ include "promgithub.fullname" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  PROMGITHUB_WEBHOOK_SECRET: "{{ .Values.secrets.github_webhook_secret }}"
  {{- if or .Values.redis.enabled .Values.redisConfig.addr }}
  PROMGITHUB_REDIS_PASSWORD: "{{ default .Values.secrets.redis_password .Values.redis.auth.password }}"
  {{- end }}
