name: Build promgithub

on:
  schedule:
    - cron: '0 15 * * 0'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    name: Build promgithub
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup environment
        id: environment
        run: |
          source version
          GOVERSION=$(make go-version)
          echo "GOVERSION=${GOVERSION}" >> $GITHUB_ENV
          echo "DOCKER_BUILDKIT=1" >> $GITHUB_ENV
          echo "DOCKER_CLI_EXPERIMENTAL=enabled" >> $GITHUB_ENV

      - name: Set up Golang
        uses: actions/setup-go@v4
        id: go
        with:
          go-version: ${{ env.GOVERSION }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.3.0
          only-new-issues: true
          args: --config=./.golangci.yaml

      - name: Security check
        uses: securego/gosec@v2.22.7
        with:
          args: ./...

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Coverage
        run: make coverage

      - name: Build Container
        run: make container
