name: Build promgithub

on:
  schedule:
    - cron: '0 15 * * 0'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read
  security-events: write

jobs:
  build:
    name: Build promgithub
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup environment
        id: environment
        run: |
          source version
          GOVERSION=$(make go-version)
          echo "GOVERSION=${GOVERSION}" >> $GITHUB_ENV
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "GOSEC_VERSION=v2.22.7" >> $GITHUB_ENV
          echo "DOCKER_BUILDKIT=1" >> $GITHUB_ENV
          echo "DOCKER_CLI_EXPERIMENTAL=enabled" >> $GITHUB_ENV

      - name: Set up Golang
        uses: actions/setup-go@v4
        id: go
        with:
          go-version: ${{ env.GOVERSION }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.3.0
          only-new-issues: true
          args: --config=./.golangci.yaml

      - name: Install Tools and Dependencies
        run: |
          # Install gosec for static security analysis
          curl -sfL https://raw.githubusercontent.com/securego/gosec/master/install.sh |\
            sh -s -- -b $(go env GOPATH)/bin "${{ env.GOSEC_VERSION }}"
          # Install dependencies
          make deps


      - name: Security Scan
        run: make security

      - name: Upload Security Scan Results
        if: always()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: build/gosec-report.sarif

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Coverage
        run: make coverage

      - name: Build Container
        run: make container

      - name: Container Security Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/darthfork/promgithub:${{ env.VERSION }}'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
